name: dependencies-builder

on:
  workflow_dispatch:
  push:

env:
  SYNC_DATESTAMP: "2024-11-04"
  ROS_DISTRO: humble

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      DEB_DISTRO: jammy
    steps:
      - name: ROS buildfarm
        uses: jspricke/ros-deb-builder-action@main
        with:
          DEB_DISTRO: ${{ env.DEB_DISTRO }}
          ROS_DISTRO: ${{ env.ROS_DISTRO }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_ROS_REPOSITORY: true
          SBUILD_CONF: |
            $extra_repositories = ["deb http://snapshots.ros.org/${{ env.ROS_DISTRO }}/${{ env.SYNC_DATESTAMP }}/ubuntu ${{ env.DEB_DISTRO }} main"];
            $extra_repository_keys = ["/home/runner/work/moveit-builder/moveit-builder/ros.key"];
            $enable_network = 1;
          SQUASH_HISTORY: true
          REPOS_FILE: sources.repos
          PACKAGES_BRANCH: stable-${{ env.SYNC_DATESTAMP }}
